# .cnb.yml
"**":
  push:
    - imports:
        - https://cnb.cool/tencent/cherry-markdown/cherry-markdown-secret/-/blob/main/secret.yml
      stages:
        # cnb 同步代码到 github 仓库 https://cnb.cool/cnb/plugins/tencentcom/git-sync#%E4%BB%8E-cnb-%E5%90%8C%E6%AD%A5%E5%88%B0-github
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/Tencent/cherry-markdown.git
            auth_type: https
            username: ${CHERRY_MARKDOWN_USERNAME}
            password: ${CHERRY_MARKDOWN_GITHUB_TOKEN}
            insecure_skip_verify: true
            timeout: 300
$:            
  vscode:
    - docker:
        image: docker.cnb.cool/tencent/cherry-markdown/cherry-markdown
        # build: .cnb/Dockerfile
        volumes:
          - node_modules
      services:
        - vscode
        - docker
      stages:
        - name: install dependencies
          script: 
          - yarn install             