const tdesignIcons = [
  { uEA0A_bold: 'textformat-bold' },
  { uEA0B_code: 'code' },
  { uEA0C_color: 'textformat-color' },
  { uEA0D_header: 'letters-h' }, // ❗️
  { uEA0E_image: 'image' }, // ❗️
  { uEA0F_italic: 'textformat-italic' },
  // { uEA1F_insertClass: 'insertClass' },
  // { uEA2A_toc: 'bulletpoint' },
  { uEA2D_sub: 'subscript' }, // ❌
  { uEA2E_sup: 'superscript' }, // ❌
  // { uEA2F_h1: 'h1' },
  { uEA03_list: 'bulletpoint' },
  { uEA04_check: 'check-rectangle' },
  { uEA5A_create: 'create' }, // ❓
  { uEA5B_download: 'download' },
  // { uEA5C_edit: 'edit' },
  { uEA5D_export: 'export' },
  { uEA5E_folderOpen: 'folder-open-1' },
  { uEA5F_folder: 'folder-1' },
  { uEA6A_primary: 'info-circle' },
  { uEA6B_warning: 'error-triangle' },
  // { uEA6C_justify: 'align' },
  { uEA6D_justifyCenter: 'format-vertical-align-center' },
  { uEA6E_justifyLeft: 'format-vertical-align-left' },
  { uEA6F_justifyRight: 'format-vertical-align-right' },
  { uEA7A_command: 'command' },
  { uEA7B_search: 'search' },
  { uEA7C_alignCenter: 'format-vertical-align-center' },
  // { uEA7D_alignJustify: 'alignJustify' },
  { uEA7E_alignLeft: 'format-vertical-align-left' },
  { uEA7F_alignRight: 'format-vertical-align-right' },
  { uEA8A_insertLineChart: 'chart-line' },
  { uEA8B_insertBarChart: 'chart-bar' },
  { uEA8C_insertRadarChart: 'chart-radar' },
  { uEA8D_insertMapChart: 'map-bubble' },
  { uEA8E_insertHeatmapChart: 'insertHeatmapChart' },
  { uEA8F_insertPieChart: 'insertPieChart' },
  { uEA09_square: 'square' },
  { uEA10_link: 'link' },
  { uEA11_ol: 'ol' },
  { uEA12_size: 'size' },
  { uEA13_strike: 'strike' },
  { uEA14_table: 'table' },
  { uEA15_ul: 'ul' },
  { uEA16_underline: 'underline' },
  { uEA17_word: 'word' },
  { uEA18_blockquote: 'blockquote' },
  { uEA19_font: 'font' },
  { uEA20_insertFlow: 'insertFlow' },
  { uEA21_insertFormula: 'insertFormula' },
  { uEA22_insertGantt: 'insertGantt' },
  { uEA23_insertGraph: 'insertGraph' },
  { uEA24_insertPie: 'insertPie' },
  { uEA25_insertSeq: 'insertSeq' },
  { uEA26_insertState: 'insertState' },
  { uEA27_line: 'line' },
  { uEA28_preview: 'preview' },
  { uEA29_previewClose: 'previewClose' },
  { uEA30_h2: 'h2' },
  { uEA31_h3: 'h3' },
  { uEA32_h4: 'h4' },
  { uEA33_h5: 'h5' },
  { uEA34_h6: 'h6' },
  { uEA35_video: 'video' },
  { uEA36_insert: 'insert' },
  { uEA37_littleTable: 'littleTable' },
  { uEA38_pdf: 'pdf' },
  { uEA39_checklist: 'checklist' },
  { uEA40_close: 'close' },
  { uEA41_fullscreen: 'fullscreen' },
  { uEA42_minscreen: 'minscreen' },
  { uEA43_insertChart: 'insertChart' },
  { uEA44_question: 'question' },
  { uEA45_settings: 'settings' },
  { uEA46_ok: 'ok' },
  { uEA47_br: 'br' },
  { uEA48_normal: 'normal' },
  { uEA49_undo: 'undo' },
  { uEA50_redo: 'redo' },
  { uEA51_copy: 'copy' },
  { uEA52_phone: 'phone' },
  { uEA53_cherryTableDelete: 'cherryTableDelete' },
  { uEA54_cherryTableInsertBottom: 'cherryTableInsertBottom' },
  { uEA55_cherryTableInsertLeft: 'cherryTableInsertLeft' },
  { uEA56_cherryTableInsertRight: 'cherryTableInsertRight' },
  { uEA57_cherryTableInsertTop: 'cherryTableInsertTop' },
  { uEA58_sortS: 'sortS' },
  { uEA59_pinyin: 'pinyin' },
  { uEA60_help: 'help' },
  { uEA61_penFill: 'penFill' },
  { uEA62_pen: 'pen' },
  { uEA64_tips: 'tips' },
  { uEA65_warn: 'warn' },
  { uEA66_mistake: 'mistake' },
  { uEA67_success: 'success' },
  { uEA68_danger: 'danger' },
  { uEA69_info: 'info' },
  { uEA70_chevronsLeft: 'chevronsLeft' },
  { uEA71_chevronsRight: 'chevronsRight' },
  { uEA72_trendingUp: 'trendingUp' },
  { uEA74_codeBlock: 'codeBlock' },
  { uEA75_expand: 'expand' },
  { uEA76_unExpand: 'unExpand' },
  { uEA77_swapVert: 'swapVert' },
  { uEA78_swap: 'swap' },
  { uEA79_keyboard: 'keyboard' },
  { uEA80_align: 'align' },
  { uEA81_imgDecoBorder: 'imgDecoBorder' },
  { uEA82_imgDecoShadow: 'imgDecoShadow' },
  { uEA83_imgDecoRadius: 'imgDecoRadius' },
  { uEA84_imgAlignLeft: 'imgAlignLeft' },
  { uEA85_imgAlignCenter: 'imgAlignCenter' },
  { uEA86_imgAlignRight: 'imgAlignRight' },
  { uEA87_imgAlignFloatLeft: 'imgAlignFloatLeft' },
  { uEA88_imgAlignFloatRight: 'imgAlignFloatRight' },
  { uEA90_insertScatterChart: 'insertScatterChart' },
  { uEA91_insertSankeyChart: 'insertSankeyChart' },
  { uEA92_menu: 'menu' },
  { uEA94_mainTheme: 'mainTheme' },
  { uEA95_codeTheme: 'codeTheme' },
];
