name: 🐞 Bug Report
description: Report a bug
title: "[Bug Report]"
labels: [🐞bug, pending-no-confirmed]
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to report this bug.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: "Before submitting the issue, ensure the following:"
      options:
        - label: There isn't an existing issue that reports the same bug to avoid duplicates.
        - label: |
            The provided information offers a [minimal reproducible example](https://github.com/Tencent/cherry-markdown/tree/main/examples) of the bug, ([Why create a Minimal](https://stackoverflow.com/help/minimal-reproducible-example)).
        - label: |
            For [Q&A](https://github.com/Tencent/cherry-markdown/discussions/categories/q-a), please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.

  - type: input
    id: version
    attributes:
      label: Version
      description: Providing the current version of cherry-markdown that will generate bugs.
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Reproduction Link
      description: A [minimal reproduction](https://github.com/Tencent/cherry-markdown/tree/main/examples) is **required**. It helps us resolve your issue faster and more effectively.
      placeholder: Reproduction Link

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      description: Provide a clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: Output of `npx envinfo --system --binaries --browsers`
      render: Shell
      placeholder: System, Binaries, Browsers

  - type: dropdown
    id: help-us
    attributes:
      label: Contributing
      description: Would you consider contributing a PR for this issue?
      options:
        - Yes, I would like to submit a PR for this issue.
        - No, I don't plan to at this time.
