name: 🔌 VSCode Plugin Feedback
description: About VSCode Plugin issue
title: "[VSCode Plugin]"
labels: [🔌vscode-plugin, pending-no-confirmed]
body:
  - type: markdown
    attributes:
      value: Thank you for your interest in the project and for taking the time to provide your feedback.

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What type of issue is this?
      options:
        - Bug Report
        - Feature Request
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: If it is a bug, please tell us which version the bug occurred in. If it is a Feature, please tell us which version you are currently using.
      placeholder: v1.0.0
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Clear and concise description of the problem or idea.
      placeholder: Questions or ideas.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.

  - type: dropdown
    id: help-us
    attributes:
      label: Help us
      description: Do you plan to submit a PR for this issue?
      options:
        - Yes, I would like to try submitting a PR for this issue.
        - No, I don't want to do it now.
