name: 🐞 Bug report
description: Report an issue for bug
title: '[Bug report]'
labels: [Bug report]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true
  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: A [minimal reproduction](https://github.com/Tencent/cherry-markdown/tree/main/examples) is **required**,It is beneficial for solving your problem faster and better.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --binaries --browsers`
      render: Shell
      placeholder: System, Binaries, Browsers
    validations:
      required: true
  - type: checkboxes
    id: validations
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Check that this is a concrete bug. For Q&A, please open a [GitHub Discussion](https://github.com/Tencent/cherry-markdown/discussions) instead.
          required: true
        - label: The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
          required: true
  - type: dropdown
    id: help-us
    attributes:
      label: Help us
      description: Do you plan to submit a PR for this issue? 
      options:
        - Yes, I would like to try submitting a PR for this issue.
        - No, I don't want to do it now.
