name: 💻 Client Feedback
description: Client feedback
title: '[Client]'
labels: [client]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in the project and for taking the time to provide your feedback.
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: 'Before submitting the issue, ensure the following:'
      options:
        - label: There isn't an existing issue that requests the same feature, to avoid duplicates.
  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What type of issue is this? 
      options:
        - Bug Report
        - Feature Request
    validations:
        required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Description of the Problem or Idea
      placeholder: Describe your questions or share your ideas here.
    validations:
      required: true
  - type: textarea
    id: further-info
    attributes:
      label: Further Information
      description: Provide any other relevant information or screenshots about the feature request here.
  - type: dropdown
    id: help-us
    attributes:
      label: Contributing
      description: Would you consider contributing a PR for this issue?
      options:
        - Yes, I'd like to submit a PR for this issue.
        - No, I don't plan to at this time.
