name: 🔌 VSCode Plugin issue
description: About VSCode Plugin issue
title: '[VSCode Plugin]'
labels: [VSCode Plugin]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature report!
  - type: dropdown
    id: type
    attributes:
      label: issue type
      description: What type of issue is this about VSCode Plugin? 
      options:
        - Bug
        - Feature
    validations:
        required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Clear and concise description of the problem or idea.
      placeholder: Questions or ideas.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
  - type: dropdown
    id: help-us
    attributes:
      label: Help us
      description: Do you plan to submit a PR for this issue? 
      options:
        - Yes, I would like to try submitting a PR for this issue.
        - No, I don't want to do it now.
