/** 工具栏按钮名称映射（英文 key -> 中文名称） */
export const TOOLBAR_BUTTON_LABELS: Record<string, string> = {
  bold: '加粗',
  italic: '斜体',
  strikethrough: '删除线',
  sub: '下标',
  sup: '上标',
  header: '标题',
  list: '列表',
  ol: '有序列表',
  ul: '无序列表',
  checklist: '检查列表',
  graph: '图形',
  size: '尺寸',
  h1: '一级标题',
  h2: '二级标题',
  h3: '三级标题',
  color: '颜色',
  quote: '引用',
  quickTable: '快速表格',
  togglePreview: '切换预览',
  code: '代码',
  inlineCode: '内联代码',
  codeTheme: '代码主题',
  export: '导出',
  settings: '设置',
  fullScreen: '全屏',
  mobilePreview: '移动预览',
  copy: '复制',
  undo: '撤销',
  redo: '重做',
  underline: '下划线',
  switchModel: '切换模型',
  image: '图像',
  audio: '音频',
  video: '视频',
  br: '换行',
  hr: '水平线',
  formula: '公式',
  link: '链接',
  table: '表格',
  toc: '目录',
  proTable: '表格图表',
  pdf: 'PDF',
  word: 'Word',
  ruby: 'Ruby',
  theme: '主题',
  file: '文件',
  panel: '信息面板',
  align: '对齐',
  detail: '手风琴',
  drawIo: 'DrawIo',
  wordCount: '字数统计',
  cursorPosition: '光标位置',
  changeLocale: '切换语言',
  shortcutKey: '快捷键',
  search: '搜索',
};

export function getButtonLabel(value: string): string {
  return TOOLBAR_BUTTON_LABELS[value] || value;
}
