/** Commands whose Cherry menu transforms selected Markdown into new Markdown. */
export const TRANSFORMED_MARKDOWN_COMMANDS = new Set([
  'align',
  'audio',
  'checklist',
  'detail',
  'draw.io',
  'file',
  'formula',
  'graph',
  'image',
  'insert',
  'link',
  'panel',
  'proTable',
  'quickTable',
  'ruby',
  'timeline',
  'toc',
  'video',
  'tips',
  'info',
  'warning',
  'danger',
  'success',
  'pinyin',
  'lineTable',
  'barTable',
  'radarTable',
  'mapTable',
  'heatmapTable',
  'scatterTable',
  'sankeyTable',
  'pieTable',
  'insertFlow',
  'insertSeq',
  'insertState',
  'insertClass',
  'insertPie',
  'insertGantt',
]);

/** Commands that transform the complete source line when the selection is empty. */
export const CHERRY_LINE_TRANSFORM_COMMANDS = new Set(['ol', 'ul', 'checklist', 'panel', 'detail', 'timeline']);

/** Inline commands that are invalid while the selection touches a code block. */
export const INLINE_FORMAT_COMMANDS = new Set([
  'bold',
  'italic',
  'strikethrough',
  'inlineCode',
  'underline',
  'sub',
  'sup',
  'size',
  'color',
]);

/** Cherry UI commands that must remain owned by Cherry instead of transforming Markdown. */
export const KNOWN_NON_TRANSFORM_COMMANDS = new Set([
  'bold',
  'italic',
  'strikethrough',
  'inlineCode',
  'code',
  'codeBlock',
  'quote',
  'hr',
  'table',
  'header',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'undo',
  'redo',
  'underline',
  'sub',
  'sup',
  'size',
  'color',
  'mobilePreview',
  'copy',
  'theme',
  'codeTheme',
  'fullScreen',
  'export',
  'changeLocale',
  'wordCount',
  'shortcutKey',
  'search',
  'togglePreview',
]);
