/**
 * Cherry Markdown 配置数据模块
 * 基于 Cherry.config.js 整理的常用可视化配置项
 * @see https://github.com/Tencent/cherry-markdown/blob/dev/packages/cherry-markdown/src/Cherry.config.js
 */

// 所有可用的工具栏按钮（'|' 为分割线，可多次使用）
export const TOOLBAR_BUTTONS = [
  'bold', 'italic', 'strikethrough', 'sub', 'sup',
  'header', 'list', 'ol', 'ul', 'checklist', 'insert',
  'graph', 'size', 'color', 'quote', 'quickTable',
  'togglePreview', 'code', 'inlineCode', 'codeTheme', 'export',
  'settings', 'fullScreen', 'undo', 'redo', 'underline',
  'switchModel', 'image', 'audio', 'video', 'br',
  'hr', 'formula', 'link', 'table', 'toc',
  'proTable', 'pdf', 'word', 'ruby', 'theme',
  'file', 'panel', 'align', 'detail', 'drawIo',
  'wordCount', 'cursorPosition', 'changeLocale', 'shortcutKey', 'search', '|'
];

// 顶部右对齐工具栏按钮（'|' 为分割线，可多次使用）
export const TOOLBAR_RIGHT_BUTTONS = [
  'bold', 'italic', 'strikethrough', 'sub', 'sup',
  'header', 'list', 'ol', 'ul', 'checklist',
  'graph', 'size', 'color', 'quote', 'quickTable',
  'togglePreview', 'code', 'inlineCode', 'codeTheme', 'export',
  'settings', 'fullScreen', 'undo', 'redo', 'underline',
  'switchModel', 'image', 'audio', 'video', 'br',
  'hr', 'formula', 'link', 'table', 'toc',
  'proTable', 'pdf', 'word', 'ruby', 'theme',
  'file', 'panel', 'align', 'detail', 'drawIo',
  'mobilePreview', 'copy', 
  'wordCount', 'cursorPosition', 'changeLocale', 'shortcutKey', 'search', '|'
];

// 气泡工具栏按钮（'|' 为分割线，可多次使用）
export const BUBBLE_BUTTONS = [
  'bold', 'italic', 'strikethrough', 'sub', 'sup',
  'header', 'list', 'ol', 'ul', 'checklist',
  'size', 'color', 'quote', 'code', 'inlineCode','underline','link', 'table',
  'ruby', 'panel', 'align', 'detail','|'
];

// 浮动工具栏按钮（'|' 为分割线，可多次使用）
export const FLOAT_BUTTONS = [
  'header', 'list', 'ol', 'ul', 'checklist',
  'graph', 'quote', 'quickTable', 'code', 
  'image', 'audio', 'video', 'br',
  'hr', 'formula', 'link', 'table', 'toc',
  'proTable', 'pdf', 'word', 'theme',
  'file', 'panel', 'align', 'detail', 'drawIo',
  '|'
];

// 侧边栏按钮（'|' 为分割线，可多次使用）
export const SIDEBAR_BUTTONS = [
  'togglePreview', 'export', 'settings', 'fullScreen', 'switchModel', 'mobilePreview', 'copy', 'theme', 'wordCount', 'changeLocale', 'shortcutKey', 'search', '|'
];

// 配置分类定义
export const CONFIG_CATEGORIES = [
  {
    id: 'basic',
    name: '基础配置',
    icon: 'fa-solid fa-gear',
    iconBg: 'bg-blue-50',
    iconColor: 'text-blue-500',
    description: '编辑器基本参数设置',
    items: [
      {
        key: 'id',
        name: '挂载节点 ID',
        path: 'id',
        type: 'string',
        description: '编辑器挂载的 DOM 节点 ID',
        inputType: 'text',
        initialValue: 'cherry-markdown',
      },
      {
        key: 'value',
        name: '初始内容',
        path: 'value',
        type: 'string',
        description: '编辑器初始化时的 Markdown 内容',
        inputType: 'textarea',
        initialValue: '# Hello Cherry Markdown!\n\n这是一个配置生成器的预览示例。\n\n## 功能特性\n\n- **粗体** 和 *斜体*\n- ~~删除线~~\n- `行内代码`\n\n```javascript\nconst cherry = new Cherry(config);\n```\n\n> 引用文本\n\n| 表头1 | 表头2 | 表头3 |\n|-------|-------|-------|\n| 内容1 | 内容2 | 内容3 |\n| 内容4 | 内容5 | 内容6 |\n\n- [x] 已完成任务\n- [ ] 待完成任务\n',
      },
      {
        key: 'isPreviewOnly',
        name: '纯预览模式',
        path: 'isPreviewOnly',
        type: 'boolean',
        description: '是否开启纯预览模式，开启后只能预览不能编辑',
        inputType: 'toggle',
      },
      {
        key: 'autoScrollByCursor',
        name: '光标自动滚动',
        path: 'autoScrollByCursor',
        type: 'boolean',
        description: '是否自动根据光标位置滚动预览区域',
        inputType: 'toggle',
      },
      {
        key: 'forceAppend',
        name: '强制输出到 body',
        path: 'forceAppend',
        type: 'boolean',
        description: '是否强制将编辑器输出到 body 上',
        inputType: 'toggle',
      },
      {
        key: 'locale',
        name: '语言设置',
        path: 'locale',
        type: 'string',
        description: '编辑器界面语言',
        inputType: 'select',
        options: ['zh_CN', 'en_US', 'zh_TW'],
      },
      {
        key: 'nameSpace',
        name: '缓存命名空间',
        path: 'nameSpace',
        type: 'string',
        description: 'cherry 缓存的作用范围，相同 nameSpace 的实例共享 localStorage 缓存',
        inputType: 'text',
      },
      {
        key: 'autoScrollByHashAfterInit',
        name: '初始化后 Hash 滚动',
        path: 'autoScrollByHashAfterInit',
        type: 'boolean',
        description: 'cherry 初始化后是否检查 location.hash 尝试滚动到对应位置',
        inputType: 'toggle',
      },
    ],
  },
  {
    id: 'editor',
    name: '编辑器配置',
    icon: 'fa-solid fa-pen-to-square',
    iconBg: 'bg-green-50',
    iconColor: 'text-green-500',
    description: 'CodeMirror 编辑器相关设置',
    items: [
      {
        key: 'editor.height',
        name: '编辑器高度',
        path: 'editor.height',
        type: 'string',
        description: '编辑器高度，支持 px 和 % 单位',
        inputType: 'text',
      },
      {
        key: 'editor.defaultModel',
        name: '默认模式',
        path: 'editor.defaultModel',
        type: 'string',
        description: '编辑器初始化后的默认模式',
        inputType: 'select',
        options: ['edit&preview', 'editOnly', 'previewOnly'],
      },
      {
        key: 'editor.convertWhenPaste',
        name: '粘贴自动转换',
        path: 'editor.convertWhenPaste',
        type: 'boolean',
        description: '粘贴时是否自动将 HTML 转成 Markdown',
        inputType: 'toggle',
      },
      {
        key: 'editor.keyMap',
        name: '快捷键风格',
        path: 'editor.keyMap',
        type: 'string',
        description: '快捷键风格，目前仅支持 sublime 和 vim',
        inputType: 'select',
        options: ['sublime', 'vim'],
      },
      {
        key: 'editor.writingStyle',
        name: '书写风格',
        path: 'editor.writingStyle',
        type: 'string',
        description: '书写风格：normal 普通 | typewriter 打字机（光标始终在屏幕中间）| focus 专注（当前行高亮）',
        inputType: 'select',
        options: ['normal', 'typewriter', 'focus'],
      },
      {
        key: 'editor.showFullWidthMark',
        name: '高亮全角符号',
        path: 'editor.showFullWidthMark',
        type: 'boolean',
        description: '是否高亮全角符号（·|￥|、|：等）',
        inputType: 'toggle',
      },
      {
        key: 'editor.showSuggestList',
        name: '显示联想框',
        path: 'editor.showSuggestList',
        type: 'boolean',
        description: '是否显示输入联想框',
        inputType: 'toggle',
      },
      {
        key: 'editor.maxUrlLength',
        name: 'URL 最大长度',
        path: 'editor.maxUrlLength',
        type: 'number',
        description: 'URL 的最大长度，-1 表示不限制，超过该长度的 URL 会显示省略号',
        inputType: 'text',
      },
    ],
  },
  {
    id: 'toolbars',
    name: '工具栏配置',
    icon: 'fa-solid fa-screwdriver-wrench',
    iconBg: 'bg-purple-50',
    iconColor: 'text-purple-500',
    description: '工具栏按钮和显示设置',
    items: [
      {
        key: 'toolbars.toolbar',
        name: '顶部工具栏按钮',
        path: 'toolbars.toolbar',
        type: 'array',
        description: '顶部工具栏显示的按钮列表，设为 false 可关闭顶部工具栏',
        inputType: 'toolbar-select',
        options: TOOLBAR_BUTTONS,
        canDisable: true,
      },
      {
        key: 'toolbars.toolbarRight',
        name: '顶部右对齐工具栏按钮',
        path: 'toolbars.toolbarRight',
        type: 'array',
        description: '顶部右对齐工具栏显示的按钮列表，设为 false 可关闭顶部右对齐工具栏',
        inputType: 'toolbar-select',
        options: TOOLBAR_RIGHT_BUTTONS,
        canDisable: true,
      },
      {
        key: 'toolbars.bubble',
        name: '气泡工具栏按钮',
        path: 'toolbars.bubble',
        type: 'array',
        description: '选中文字时弹出的气泡工具栏按钮，设为 false 可关闭气泡工具栏',
        inputType: 'toolbar-select',
        options: BUBBLE_BUTTONS,
        canDisable: true,
      },
      {
        key: 'toolbars.float',
        name: '浮动工具栏按钮',
        path: 'toolbars.float',
        type: 'array',
        description: '新行出现的浮动工具栏按钮，设为 false 可关闭浮动工具栏',
        inputType: 'toolbar-select',
        options: FLOAT_BUTTONS,
        canDisable: true,
      },
      {
        key: 'toolbars.sidebar',
        name: '侧边栏按钮',
        path: 'toolbars.sidebar',
        type: 'array',
        description: '侧边栏工具栏按钮，设为 false 可关闭侧边栏',
        inputType: 'toolbar-select',
        options: SIDEBAR_BUTTONS,
        canDisable: true,
        initialValue: ['mobilePreview', 'copy', 'theme'],
      },
    ],
  },
  {
    id: 'engine-global',
    name: '引擎全局配置',
    icon: 'fa-solid fa-globe',
    iconBg: 'bg-cyan-50',
    iconColor: 'text-cyan-500',
    description: 'Markdown 解析引擎全局设置',
    items: [
      {
        key: 'engine.global.classicBr',
        name: '经典换行',
        path: 'engine.global.classicBr',
        type: 'boolean',
        description: '是否启用经典换行逻辑（true: 一个换行被忽略，两个换行分段）',
        inputType: 'toggle',
      },
      {
        key: 'engine.global.htmlWhiteList',
        name: 'HTML 白名单',
        path: 'engine.global.htmlWhiteList',
        type: 'string',
        description: '额外允许渲染的 HTML 标签，标签以英文竖线分隔，如：iframe|script|style',
        inputType: 'text',
      },
      {
        key: 'engine.global.htmlBlackList',
        name: 'HTML 黑名单',
        path: 'engine.global.htmlBlackList',
        type: 'string',
        description: 'HTML 黑名单，优先级高于白名单，标签以英文竖线分隔，配置 * 可禁用所有 HTML 标签',
        inputType: 'text',
      },
      {
        key: 'engine.global.htmlAttrWhiteList',
        name: 'HTML 属性白名单',
        path: 'engine.global.htmlAttrWhiteList',
        type: 'string',
        description: '额外允许渲染的 HTML 标签属性，标签以英文竖线分隔，如：part|onmouseover|my-attr',
        inputType: 'text',
      },
      {
        key: 'engine.global.flowSessionContext',
        name: '流式会话模式',
        path: 'engine.global.flowSessionContext',
        type: 'boolean',
        description: '适配流式会话场景，开启后渲染频率提升、代码块/表格等自动闭合',
        inputType: 'toggle',
      },
      {
        key: 'engine.global.flowSessionCursor',
        name: '流式会话光标',
        path: 'engine.global.flowSessionCursor',
        type: 'string',
        description: "流式会话时在末尾增加光标 DOM，'default' 使用默认样式，'' 不增加",
        inputType: 'text',
      },
    ],
  },
  {
    id: 'engine-syntax',
    name: '语法配置',
    icon: 'fa-solid fa-code',
    iconBg: 'bg-orange-50',
    iconColor: 'text-orange-500',
    description: 'Markdown 语法解析规则设置',
    items: [
      {
        key: 'engine.syntax.autoLink',
        name: '自动链接',
        path: 'engine.syntax.autoLink',
        type: 'object',
        description: '自动识别并转换 URL 为可点击链接',
        inputType: 'toggle',
        subItems: [
          { key: 'enableShortLink', name: '启用短链接', type: 'boolean' },
          { key: 'shortLinkLength', name: '短链接长度', type: 'number' },
        ],
      },
      {
        key: 'engine.syntax.list',
        name: '列表',
        path: 'engine.syntax.list',
        type: 'object',
        description: '有序/无序列表解析配置',
        inputType: 'toggle',
        subItems: [
          { key: 'listNested', name: '同级列表类型转换', type: 'boolean' },
          { key: 'indentSpace', name: '缩进空格数', type: 'number' },
        ],
      },
      {
        key: 'engine.syntax.table',
        name: '表格',
        path: 'engine.syntax.table',
        type: 'object',
        description: '表格解析配置，支持渲染为图表',
        inputType: 'toggle',
        subItems: [
          { key: 'enableChart', name: '启用图表渲染', type: 'boolean' },
        ],
      },
      {
        key: 'engine.syntax.inlineCode',
        name: '行内代码',
        path: 'engine.syntax.inlineCode',
        type: 'object',
        description: '行内代码解析配置',
        inputType: 'toggle',
        subItems: [
          { key: 'showColor', name: '颜色值显示色块', type: 'boolean' },
          { key: 'selfClosing', name: '自动闭合', type: 'boolean' },
        ],
      },
      {
        key: 'engine.syntax.codeBlock',
        name: '代码块',
        path: 'engine.syntax.codeBlock',
        type: 'object',
        description: '代码块渲染配置',
        inputType: 'toggle',
        subItems: [
          { key: 'wrap', name: '自动换行', type: 'boolean' },
          { key: 'lineNumber', name: '显示行号', type: 'boolean' },
          { key: 'copyCode', name: '复制按鈕', type: 'boolean' },
          { key: 'editCode', name: '编辑按鈕', type: 'boolean' },
          { key: 'changeLang', name: '语言切换', type: 'boolean' },
          { key: 'expandCode', name: '展开/折叠按鈕', type: 'boolean' },
          { key: 'selfClosing', name: '自动闭合', type: 'boolean' },
          { key: 'indentedCodeBlock', name: '缩进代码块', type: 'boolean' },
        ],
      },      {
        key: 'engine.syntax.emoji',
        name: 'Emoji 表情',
        path: 'engine.syntax.emoji',
        type: 'object',
        description: 'Emoji 表情渲染配置',
        inputType: 'toggle',
        subItems: [
          { key: 'useUnicode', name: '使用 Unicode 渲染', type: 'boolean' },
        ],
      },
      {
        key: 'engine.syntax.fontEmphasis',
        name: '字体强调',
        path: 'engine.syntax.fontEmphasis',
        type: 'object',
        description: '粗体/斜体等字体样式配置',
        inputType: 'toggle',
        subItems: [
          { key: 'allowWhitespace', name: '允许首尾空格', type: 'boolean' },
        ],
      },
      {
        key: 'engine.syntax.strikethrough',
        name: '删除线',
        path: 'engine.syntax.strikethrough',
        type: 'object',
        description: '删除线语法配置',
        inputType: 'toggle',
        subItems: [
          { key: 'needWhitespace', name: '需要首尾空格', type: 'boolean' },
        ],
      },
      {
        key: 'engine.syntax.mathBlock',
        name: '数学公式（块级）',
        path: 'engine.syntax.mathBlock',
        type: 'object',
        description: '块级数学公式渲染配置',
        inputType: 'toggle',
        subItems: [
          { key: 'engine', name: '渲染引擎', type: 'select', options: ['MathJax', 'katex'] },
          { key: 'plugins', name: '加载插件', type: 'boolean' },
        ],
      },
      {
        key: 'engine.syntax.inlineMath',
        name: '数学公式（行内）',
        path: 'engine.syntax.inlineMath',
        type: 'object',
        description: '行内数学公式渲染配置',
        inputType: 'toggle',
        subItems: [
          { key: 'engine', name: '渲染引擎', type: 'select', options: ['MathJax', 'katex'] },
        ],
      },
      {
        key: 'engine.syntax.toc',
        name: '目录 (TOC)',
        path: 'engine.syntax.toc',
        type: 'object',
        description: '目录自动生成配置',
        inputType: 'toggle',
        subItems: [
          { key: 'allowMultiToc', name: '允许多个目录', type: 'boolean' },
          { key: 'showAutoNumber', name: '显示序号', type: 'boolean' },
        ],
      },
      {
        key: 'engine.syntax.header',
        name: '标题',
        path: 'engine.syntax.header',
        type: 'object',
        description: '标题解析配置',
        inputType: 'toggle',
        subItems: [
          { key: 'anchorStyle', name: '锚点样式', type: 'select', options: ['default', 'autonumber', 'none'] },
          { key: 'strict', name: '严格模式', type: 'boolean' },
        ],
      },
      {
        key: 'engine.syntax.htmlBlock',
        name: 'HTML 块',
        path: 'engine.syntax.htmlBlock',
        type: 'object',
        description: 'HTML 块级内容渲染配置',
        inputType: 'toggle',
        subItems: [
          { key: 'filterStyle', name: '过滤 style 属性', type: 'boolean' },
          { key: 'removeTrailingNewline', name: '去掉闭合标签后连续换行', type: 'boolean' },
        ],
      },
      {
        key: 'engine.syntax.image',
        name: '图片',
        path: 'engine.syntax.image',
        type: 'object',
        description: '图片渲染配置',
        inputType: 'toggle',
        subItems: [
          { key: 'selfClosing', name: '自动闭合', type: 'boolean' },
        ],
      },
      {
        key: 'engine.syntax.link',
        name: '链接',
        path: 'engine.syntax.link',
        type: 'object',
        description: '链接渲染配置',
        inputType: 'toggle',
        subItems: [
          { key: 'target', name: '打开方式', type: 'select', options: ['_blank', '_self', '_parent', '_top'] },
          { key: 'selfClosing', name: '自动闭合', type: 'boolean' },
        ],
      },
    ],
  },
  {
    id: 'previewer',
    name: '预览器配置',
    icon: 'fa-solid fa-eye',
    iconBg: 'bg-pink-50',
    iconColor: 'text-pink-500',
    description: '预览区域相关设置',
    items: [
      {
        key: 'previewer.className',
        name: '预览区 className',
        path: 'previewer.className',
        type: 'string',
        description: '预览区域的 CSS 类名',
        inputType: 'text',
      },
      {
        key: 'previewer.enablePreviewerBubble',
        name: '预览区编辑能力',
        path: 'previewer.enablePreviewerBubble',
        type: 'boolean',
        description: '是否启用预览区域编辑能力（点击预览区可定位到编辑区）',
        inputType: 'toggle',
      },
      {
        key: 'previewer.isMobilePreview',
        name: '移动端预览',
        path: 'previewer.isMobilePreview',
        type: 'boolean',
        description: '是否启用移动端预览模式',
        inputType: 'toggle',
      },
      {
        key: 'previewer.floatWhenClosePreviewer',
        name: '关闭预览时浮动',
        path: 'previewer.floatWhenClosePreviewer',
        type: 'boolean',
        description: '关闭预览时是否浮动显示预览区域',
        inputType: 'toggle',
      },
    ],
  },
  {
    id: 'externals',
    name: '外部依赖',
    icon: 'fa-solid fa-puzzle-piece',
    iconBg: 'bg-indigo-50',
    iconColor: 'text-indigo-500',
    description: '第三方组件引入配置',
    items: [
      {
        key: 'externals.echarts',
        name: 'ECharts 图表',
        path: 'externals.echarts',
        type: 'object',
        description: '引入 ECharts 组件，用于表格渲染为图表',
        inputType: 'toggle',
      },
      {
        key: 'externals.MathJax',
        name: 'MathJax 公式',
        path: 'externals.MathJax',
        type: 'object',
        description: '引入 MathJax 组件，用于数学公式渲染',
        inputType: 'toggle',
      },
      {
        key: 'externals.katex',
        name: 'KaTeX 公式',
        path: 'externals.katex',
        type: 'object',
        description: '引入 KaTeX 组件，用于数学公式渲染',
        inputType: 'toggle',
      },
    ],
  },
  {
    id: 'themeSettings',
    name: '主题设置',
    icon: 'fa-solid fa-palette',
    iconBg: 'bg-rose-50',
    iconColor: 'text-rose-500',
    description: '编辑器主题相关设置',
    items: [
      {
        key: 'themeSettings.mainTheme',
        name: '主题',
        path: 'themeSettings.mainTheme',
        type: 'string',
        description: '编辑器主题',
        inputType: 'select',
        options: ['default', 'dark', 'gray', 'abyss', 'green', 'red', 'violet', 'blue'],
      },
      {
        key: 'themeSettings.codeBlockTheme',
        name: '代码块主题',
        path: 'themeSettings.codeBlockTheme',
        type: 'string',
        description: '代码块的高亮主题',
        inputType: 'select',
        options: ['default', 'dark', 'light', 'monokai', 'github', 'tomorrow', 'solarized-light', 'solarized-dark'],
      },
      {
        key: 'themeSettings.inlineCodeTheme',
        name: '行内代码主题',
        path: 'themeSettings.inlineCodeTheme',
        type: 'string',
        description: '行内代码的颜色主题',
        inputType: 'select',
        options: ['red', 'black'],
      },
    ],
  },
];

// 预设配置
export const PRESETS = {
  default: {
    name: '默认配置',
    description: '标准编辑器配置',
    overrides: {},
  },
  simple: {
    name: '精简模式',
    description: '轻量级编辑器',
    overrides: {
      'toolbars.toolbar': ['bold', 'italic', 'header', '|', 'list', 'code'],
      'toolbars.toolbarRight': ['togglePreview'],
      'toolbars.bubble': ['bold', 'italic', 'underline'],
      'toolbars.float': ['h1', 'h2', 'h3'],
      'toolbars.sidebar': false,
    },
  },
  full: {
    name: '完整模式',
    description: '全部功能开启',
    overrides: {
      'toolbars.toolbar': ['bold', 'italic', 'strikethrough', 'underline', '|', 'color', 'header', 'list', 'checklist', '|', 'quote', 'quickTable', 'code', 'formula', '|', 'link', 'image', 'audio', 'video', '|', 'hr', 'br', 'toc', '|', 'graph'],
      'toolbars.toolbarRight': ['togglePreview', 'export', 'settings', '|', 'undo', 'redo', 'fullScreen'],
      'toolbars.bubble': ['bold', 'italic', 'underline', 'strikethrough', 'sub', 'sup', 'quote', 'ruby', 'size', 'color'],
      'toolbars.float': ['h1', 'h2', 'h3', 'checklist', 'quote', 'quickTable', 'code'],
      'toolbars.sidebar': ['mobilePreview', 'copy', 'theme'],
    },
  },
  preview: {
    name: '纯预览模式',
    description: '只读预览',
    overrides: {
      'isPreviewOnly': true,
      'toolbars.toolbar': false,
      'toolbars.toolbarRight': false,
      'toolbars.bubble': false,
      'toolbars.float': false,
      'toolbars.sidebar': false,
      'editor.defaultModel': 'previewOnly',
    },
  },
};
