name: Preview Publish

on:
  workflow_run:
    workflows:
      - Preview Build
    types:
      - completed

jobs:
  preview-success:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    outputs:
      pr_id: ${{ steps.pr.outputs.id }}
    steps:
      - name: download pr id
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: pr-id

      - name: output pr id
        id: pr
        run: echo "id=$(<pr-id.txt)" >> $GITHUB_OUTPUT

      - name: Download playground
        uses: dawidd6/action-download-artifact@v8
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: playground

      - id: deploy
        run: |
          export DEPLOY_DOMAIN=https://preview-pr-${{ steps.pr.outputs.id }}-cherry-markdown.surge.sh
          npx surge --project ./ --domain $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}
          echo "url=$DEPLOY_DOMAIN" >> $GITHUB_OUTPUT

      - uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          body: |
            ### 【预览链接】
            * [full model](${{steps.deploy.outputs.url}}/index.html)
            * [basic](${{steps.deploy.outputs.url}}/basic.html)
            * [mobile](${{steps.deploy.outputs.url}}/h5.html)
            * [multiple instances](${{steps.deploy.outputs.url}}/multiple.html)
            * [editor without toolbar](${{steps.deploy.outputs.url}}/notoolbar.html)
            * [pure preview](${{steps.deploy.outputs.url}}/preview_only.html)
            * [XSS](${{steps.deploy.outputs.url}}/xss.html)（Not allowed by default）
            * [img wysiwyg](${{steps.deploy.outputs.url}}/img.html)
            * [table wysiwyg](${{steps.deploy.outputs.url}}/table.html)
            * [headers with auto num](${{steps.deploy.outputs.url}}/head_num.html)
            * [流式输入模式（AI chart场景）](${{steps.deploy.outputs.url}}/ai_chat.html)
            * [VIM 编辑模式](${{steps.deploy.outputs.url}}/vim.html)
            <!-- [工作流地址](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}) -->
            <!-- AUTO_PREVIEW_HOOK -->
          number: ${{ steps.pr.outputs.id }}
          body-include: '<!-- AUTO_PREVIEW_HOOK -->'

  preview-failed:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: download pr id
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: pr-id

      - name: output pr id
        id: pr
        run: echo "id=$(<pr-id.txt)" >> $GITHUB_OUTPUT

      - name: The job failed
        uses: actions-cool/maintain-one-comment@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          body: |
            预览编译失败
            <!-- [工作流地址](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}) -->
            <!-- AUTO_PREVIEW_HOOK -->
          number: ${{ steps.pr.outputs.id }}
          body-include: '<!-- AUTO_PREVIEW_HOOK -->'
