name: Preview Build

on:
  pull_request:
    branches: [dev, main]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.number }} > pr-id.txt
      - uses: actions/upload-artifact@v4
        with:
          name: pr-id
          path: pr-id.txt
          retention-days: 5

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
           node-version: lts/*
           cache: 'yarn'

      - run: yarn install

      - run: yarn build

      - run: |
            mkdir playground
            cp -r packages/cherry-markdown/dist playground
            cp -r examples/assets playground
            cp examples/*.html playground

      - uses: actions/upload-artifact@v4
        with:
          name: playground
          path: playground
          retention-days: 5
