default.check-filename = true

[default.extend-words]
ths="ths"
curren="curren"
Automattic="Automattic"
hel="hel"


[files]
extend-exclude = [
    "CHANGELOG.md",
    "packages/cherry-markdown/src/libs",
    'packages/vscodePlugin/web-resources/scripts',
    'examples/assets',
    'examples/miniProgram/miniprogram/vendor/cherry-mini-program-stream.js',
    '__snapshots__',
    'Emoji.config.js',
    'commonmark.spec.json',
    '*.nsi'
]
